name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: SSw4rtzz/academy/.github/actions/maven_build@master

    - uses: SSw4rtzz/academy/.github/actions/docker_build@master
      with:
        path_dockerfile: src/main/docker/Dockerfile.jvm
        image_name: academy
        tag_name: v1
